spring:
  application:
    name: nycloud-api-gateway
server:
  port: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
zuul:
  ribbon:
    eager-load:
      enabled: true
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
  routes:
    auth:
      path: /user/**
      serviceId: nycloud-auth-server
  retryable: true

ribbon:
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 5000
  ConnectTimeout: 5000
default:
  execution:
    isolation:
      thread:
        timeoutInMilliseconds: 60000
auth:
  permitall:
    -
      pattern: /**/public/**
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8761/oauth/token
      user-authorization-uri: http://localhost:8761/oauth/authorize
      client-id: nycloud-api-gateway
    resource:
      user-info-uri: http://localhost:8761/userinfo
      prefer-token-info: false
