spring:
  application:
    name: nycloud-api-gateway
server:
  port: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/  #服务注册中心地址
zuul:
  ribbon:
    eager-load:
      enabled: true  #zuul饥饿加载
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
  routes:
    auth:
      path: /user/**
      serviceId: nycloud-auth-server
  retryable: true

ribbon:
  MaxAutoRetries: 3  #同一个Server重试的次数(除去首次)
  MaxAutoRetriesNextServer: 0 #切换相同Server的次数
  ReadTimeout: 5000
  ConnectTimeout: 5000
default:
  execution:
    isolation:
      thread:
        timeoutInMilliseconds: 60000
auth:
  permitall: #配置不需要经过权限检查的url
    -
      pattern: /**/public/**
security:
  oauth2: #配置权限
    client:
      access-token-uri: /oauth/token
      id: gateway
      client-secret: gateway
    resource:
      user-info-uri: /user #配置userinfo的url地址
      token-info-uri: /oauth/check_token #配置check-token的url地址
