spring:
  application:
    name: nycloud-eureka
  security:
    user:
      name: admin
      password: 123456

server:
  port: 8760
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/