spring:
  application:
    name: nycloud-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
  datasource:
    url: jdbc:mysql://localhost:3306/nycloud-admin
    username: admin
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9000
  servlet:
    context-path: /




